language: python
python:
- 3.6
services:
- mysql
addons:
  apt_packages:
  - libcups2-dev
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 edc_visit_schedule
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=edc_visit_schedule manage.py test
after_success:
- coveralls
notifications:
  slack:
    secure: w+16gju/oNhL1LnYIAjQ59M7QU92VOE/06bsWK7fwMz/HrTiqSYE+VdCGlX3+VamWnvy/7MBKxzk1jXdzwxDi1fwXlCYQXKIIxf8UD56vpcVbN+IbsfaMEhsXpafSS5JTj8oXip9/Fy1XO2uIdr+Li/nya8mXQktCSUSrtWFRAO16K65BRrl0VJ36RSm15LDNLGJZLVzPdhcGrWfQd0b0zerozi/J7k2+zZGwpqu5LcB0soEpOo2w9gas08KO98JlCOTDRcrUJhnp+0te2hNGzUFm0542Py2x0QhE82RNnpHPZ5ImMSKrxbQXYYTHzKMR0LzUqXa0IO/9pQOz09OimjYs/CzbQsaU571Q5FmmZm1l3MX0H/7IH5yckAO7dk4qkNvYaha3NfQKLZHZMTeIihWkxFCAl55qRRQ3nB/zGMj6eLUwllJ4Ze+z0f2FXq4Eu2ScM9ESKw/l4nMJL7ElL3yEngLl3U+TlSj83r8cW3Cwac11bN+n5Obs+Zx8OE/7A7JqsEl2iip5Z6OPgpSFJhwfPc4n/Zco9JTNe4CfJjVfZVf+Tefj6JiqYz/YRNufM4nwZ6vehdfmXzDh6ShmcfN6DDu8H77xBE9sAYcpkynsYYHq2vi3b6CN+5cWqtV2b9DiztMnN1Um1okD2czxmvDZDk4jbHhNNEHKnLexQs=
